name: Build check

on:
  push:
    paths:
      - ".github/workflows/**"
      - "include/**"
      - "examples/**"
      - "CMakeLists.txt"

jobs:
  build-ubuntu:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake

    - name: Configure CMake
      run: cmake .

    - name: Build
      run: make
